#ifndef TEST_SENDER_H
#define TEST_SENDER_H

#define MSG_SIZE 94

enum {
  LOG_SERIAL_START_ATTEMPTS,
  LOG_RADIO_START_ATTEMPTS,
  LOG_RADIO_1_SEND,
  LOG_RADIO_2_SEND,
  LOG_RADIO_1_SEND_ERROR,
  LOG_RADIO_2_SEND_ERROR,
  LOG_RADIO_1_SEND_DONE,
  LOG_RADIO_2_SEND_DONE,
  LOG_RADIO_1_SEND_DONE_ERROR,
  LOG_RADIO_2_SEND_DONE_ERROR,
  LOG_RADIO_1_RECEIVED,
  LOG_RADIO_2_RECEIVED,
  LOG_RADIO_1_TOTAL,
  LOG_RADIO_2_TOTAL,
  LOG_RADIO_1_RECEIVED_TOTAL,
  LOG_RADIO_2_RECEIVED_TOTAL,
  LOG_ELAPSED_TIME,
  LOG_CONTROL_SEND,
  LOG_CONTROL_SEND_ERROR,
  LOG_CONTROL_SEND_DONE,
  LOG_CONTROL_SEND_DONE_ERROR,
  LOG_CONTROL_RECEIVE,
  LOG_MESSAGE_SIZE,
  LOG_PAYLOAD_SIZE,
  LOG_RADIOS_BUSY_ERROR,
  LOG_EBUSY_1_COUNT,
  LOG_EBUSY_2_COUNT,
  LOG_SEND_DONE_1_COUNT,
  LOG_SEND_DONE_2_COUNT,
};

typedef nx_struct test_msg {
  nx_uint16_t source;
  nx_uint16_t destination;
  nx_uint16_t seqno;
  nx_uint8_t data[MSG_SIZE];
} test_msg_t;

#endif
