#ifndef TEST_RECEIVER_H
#define TEST_RECEIVER_H

#define MSG_SIZE 94

enum {
  LOG_SERIAL_START_ATTEMPTS,
  LOG_RADIO_START_ATTEMPTS,
  LOG_RADIO_1_SEND,
  LOG_RADIO_2_SEND,
  LOG_RADIO_1_SEND_ERROR,
  LOG_RADIO_2_SEND_ERROR,
  LOG_RADIO_1_SEND_DONE,
  LOG_RADIO_2_SEND_DONE,
  LOG_RADIO_1_SEND_DONE_ERROR,
  LOG_RADIO_2_SEND_DONE_ERROR,
  LOG_RADIO_1_RECEIVED,
  LOG_RADIO_2_RECEIVED,
  LOG_RADIO_1_TOTAL,
  LOG_RADIO_2_TOTAL,
  LOG_RADIO_1_RECEIVED_TOTAL,
  LOG_RADIO_2_RECEIVED_TOTAL,
  LOG_ELAPSED_TIME,
  LOG_CONTROL_SEND,
  LOG_CONTROL_SEND_ERROR,
  LOG_CONTROL_SEND_DONE,
  LOG_CONTROL_SEND_DONE_ERROR,
  LOG_CONTROL_RECEIVE,
};

typedef nx_struct receiver_msg {
  nx_uint16_t source;
  nx_uint16_t destination;
  nx_uint16_t seqno;
  nx_uint8_t data[MSG_SIZE];
} receiver_msg_t;

#endif
