COMPONENT=TestCollectTopologyAppC

CFLAGS += -I$(TOSDIR)/lib/net \
					-I$(TOSDIR)/lib/net/drip \
					-I$(TOSDIR)/lib/net/ctp \
					-I$(TOSDIR)/lib/net/4bitle \
					-I../dual-link-estimator \
					-I../mpdr \
					-I../serial-logger

include $(MAKERULES)
